main: com.github.hsnyder1.Bukkit_Animal_Mod.Bukkit_Animal_Mod
name: Bukkit_Animal_Mod
version: ${project.version}
description: {project.description}
commands:
    plugin:
        description: the base for this plugin
        usage: /<plugin> command
        permission: plugin.*
permissions:
    plugin.*:
        description: permissions of all plugin commands
        default: true
        children:
            plugin.give_me_leash:
                description:  gives player the ingredients to make a leash.
            plugin.give_me_saddle:
                description: gives player saddles
            plugin.give_me_bone:
                description: gives player bones, tells them good choice
            plugin.give_me_fish:
                description: gives player fish, tells them dogs are better